- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs # Sunrise-RoleTime
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: 10
  access:
  - Research # Fire
  - Kitchen # Fire
  - Hydroponics # Fire
  - Janitor # Fire
  - Security
  - Brig
#  - Maintenance #Sunrise-Edit
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolG22NonLethal # Sunrise-Edit
  storage:
    back:
    - Flash
    - MagazineGlock22Rubber
