- type: job
  id: ExternalAdministrativeZoneOfficer
  name: job-name-external-administrative-zone-officer
  description: job-description-external-administrative-zone-officer
  playTimeTracker: JobExternalAdministrativeZoneOfficer
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 часов
  startingGear: ExternalAdministrativeZoneOfficerGear
  icon: JobExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 10
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: ExternalAdministrativeZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetExternalAdministrativeZoneSecurityService
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22
