- type: job
  id: ExternalAdministrativeZoneCommandant
  name: job-name-external-administrative-zone-commandant
  description: job-description-external-administrative-zone-commandant
  playTimeTracker: JobExternalAdministrativeZoneCommandant
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 90000 # 25 часов
  startingGear: ExternalAdministrativeZoneCommandantGear
  icon: JobExternalAdministrativeZoneCommandant
  supervisors: job-supervisors-security-commander
  canBeAntag: false
  displayWeight: 70
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Armory
  #  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: ExternalAdministrativeZoneCommandantGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltExternalAdministrativeZoneSecurityService
  storage:
    back:
    - Flash
#    - MagazineGlock22
