- type: playTimeTracker
  id: JobClassD

- type: playTimeTracker
  id: JobClassDCook

- type: playTimeTracker
  id: JobClassDBotanist

- type: playTimeTracker
  id: JobClassDJanitor

- type: playTimeTracker
  id: JobScp173

- type: playTimeTracker
  id: JobScp939

- type: playTimeTracker
  id: JobScp049

- type: playTimeTracker
  id: JobScp082

- type: playTimeTracker
  id: JobScp106

- type: playTimeTracker
  id: JobScp096

- type: playTimeTracker
  id: JobScp999
