- type: entity
  parent: ClothingHeadHelmetBasic
  id: ClothingHeadHelmetSecurity
  name: helmet
  description: Standard black security gear. Protects the head from impacts.
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Head/security.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Head/security.rsi

- type: entity
  parent: ClothingHeadHelmetBasic
  id: ClothingHeadClosedHelmetSecurity
  name: closed black security helmet
  description: Standard black security gear. Protects the head from impacts.
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Head/security_2.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Head/security_2.rsi

- type: entity
  parent: ClothingHeadHeadHatBaseFlippable
  id: ClothingHeadHatSecBlack
  name: black security cap
  description: It's a robust baseball hat in black colour.
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Head/security_cap.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Head/security_cap.rsi

- type: entity
  parent: ClothingHeadBase
  id: ClothingHeadSecurityBeret
  name: security black beret
  description: Stylish neck gaiter for your neck, can protect from the cosmic wind?...
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Head/security_beret.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Head/security_beret.rsi
