- type: job
  id: Scp049
  name: job-name-scp049
  description: job-description-scp049
  playTimeTracker: JobScp049
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp049
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp049

- type: job
  id: Scp939
  name: job-name-scp939
  description: job-description-scp939
  playTimeTracker: JobScp939
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp939
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp939

- type: job
  id: Scp173
  name: job-name-scp173
  description: job-description-scp173
  playTimeTracker: JobScp173
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp173
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp173

- type: job
  id: Scp999
  name: job-name-scp999
  description: job-description-scp999
  playTimeTracker: JobScp999
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp999
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp999

- type: job
  id: Scp096
  name: job-name-scp096
  description: job-description-scp096
  playTimeTracker: JobScp096
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp096
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp096

- type: job
  id: Scp106
  name: job-name-scp106
  description: job-description-scp106
  playTimeTracker: JobScp106
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp106
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp106

- type: job
  id: Scp082
  name: job-name-scp082
  description: job-description-scp082
  playTimeTracker: JobScp082
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 720000 # 200h
  weight: 25
  icon: JobIconScp082
  joinNotifyCrew: false
  canBeAntag: false
  jobEntity: Scp096 # TODO: Поменять после добавления каннибала
