- type: job
  id: ClassDBotanist
  name: job-name-class-d-botanist
  description: job-description-class-d
  playTimeTracker: JobClassDBotanist
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 час
  startingGear: ClassDBotanistGear
  icon: JobClassDBotanist
  supervisors: job-supervisors-security-and-research
  access:
  - Service
  - Hydroponics
  alwaysUseSpawner: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: ClassDAppearance

- type: startingGear
  id: ClassDBotanistGear
  equipment:
    head: ClothingHeadBandBotany
    jumpsuit: ClothingUniformClassD
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
    gloves: ClothingHandsGlovesLeather
    shoes: ClothingShoesClassD
    id: ClassDBotanistIDCard

